name: Build and deploy the java/maven folder

on:
  push:
    branches:
    - master
    paths:
    - '.github/**'
    - 'java/maven/**'

jobs:
  build-maven:

    runs-on: ubuntu-latest

    container:
      image: maven:3.6.3-jdk-8
      volume:
      - ./

    steps:
      
    # - name: Checkout code
    #   uses: actions/checkout@v2

    - name: Build maven
      working-directory: 'java/maven'
      run: mvn package
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: target/*.jar
        
  build-docker:
    
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: jar
    
    - name: Build docker
      run: docker build -t my-app:latest .
      
    - name: Deploy
      run: docker run my-app:latest
      
      

        
