name: Build and deploy the java/maven/my-app folder

on:
  push:
    branches:
    - master
    paths:
    - '.github/**'
    - 'java/maven/**'

jobs:
  # Checks out code, builds the project and uploads the artifact for use in another job.
  build-maven:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-jdk-8
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build maven
      working-directory: 'java/maven/my-app'
      run: mvn package
    - name: Upload artifact
      working-directory: 'java/maven/my-app'
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: target/*.jar
      
  # Downloads the artifact from a previous job and packages it into an image, then run the image.  
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: jar
    - name: Build docker
      run: docker build -t my-app:latest .
    - name: Deploy
      run: docker run my-app:latest
      
      

        
