name: Build and deploy the java/maven folder

on:
  push:
    branches:
    - master
    paths:
    - 'java/maven/*'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: maven:3.6.3-jdk-8
      # volumes:
      #   - ./

    steps:
    - name: debug
      run: |
        pwd
        ls -la 
    - name: Build maven
      working-directory: 'java/maven'
      run: |
        pwd
        ls -la 
      # run: mvn package
      
    - name: Build docker
      run: docker build my-app:latest
      
    - name: Deploy
      run: docker run my-app:latest
      
      

        
