name: Build and Deploy java/maven/my-app

on:
  push:
    branches:
    - master
    paths:
    - '.github/**'
    - 'java/maven/**'

jobs:
  # Checks out code, builds the project and uploads the artifact for use in another job.
  build-maven:
    env:
      BUILD_PATH: 'java/maven/my-app'
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-jdk-8
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build maven
      working-directory: ${{ env.BUILD_PATH }}
      run: mvn package
    - name: Rename artifact
      working-directory: ${{ env.BUILD_PATH }}/target
      run: mv *.jar app.jar
    # Uploading wildcards will be possible once a v2 of the download and upload-artifact actions comes out, see: https://github.com/actions/upload-artifact/issues/7
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: ${{ env.BUILD_PATH }}/target/app.jar
      
  # Downloads the artifact from a previous job and packages it into an image, then run the image.  
  build-docker:
    needs: build-maven
    runs-on: ubuntu-latest
    steps:
    # Uploading wildcards will be possible once a v2 of the download and upload-artifact actions comes out, see: https://github.com/actions/upload-artifact/issues/7
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: jar
    - name: Build docker
      run: docker build -t my-app:latest .
    - name: Deploy
      run: docker run my-app:latest
      
      

        
