name: Build python/echo

on:
  push:
    branches:
    - master
    paths:
    - '.github/**'
    - 'python/echo/**'

env:
  BUILD_PATH: 'python/echo'

jobs:
  # Packages file into an image, then runs the image.  
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code for the dockerfile
      uses: actions/checkout@v2
    - name: Build docker
      working-directory: ${{ env.BUILD_PATH }}
      run: docker build -t my-app:latest .
    - name: Deploy
      run: docker run my-app:latest
      
      

        
